[address]
home_server_ip = "<Home Server Ip>"
home_server_macaddress = "<MACADDRESS>"
home_server_port = "<Port> : int"
home_server_wol_port = "<Port> : int"
valheim_confirmation_port = "<Port> : int"

[discord]
administrator = ["<ADMIN ID> : int"]
prefix = "~"
token = "<Discord token>"

[gameinfo]
sdtd_password = "<pass>"

[log]
term_log = "debug"
write_log = "off"

[secret]
openai_api_key = "<API_KEY>"
rinna_cce_subscription_key = "<API_KEY>"
rinna_subscription_key = "<API_KEY>"

[path]
firefox_profile = "<FIREFOX PROFILE PATH>"
geckodriver_path = "<Driver PATH>"
python = "<Python PATH>"
