# This is a basic workflow to help you get started with Actions

name: Release and deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
      - "v*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          components: rustfmt, clippy
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all-features
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --target x86_64-unknown-linux-gnu
      - uses: actions/upload-artifact@v2
        with:
          name: binary_artifact
          path: |
            target/x86_64-unknown-linux-gnu/release/discord_bot_client
            target/x86_64-unknown-linux-gnu/release/homeserver_receive_process
            target/x86_64-unknown-linux-gnu/release/valheim-connection-check

  deploy:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: binary_artifact
          path: ./
      - name: make release package
        run: |
          mkdir -p ${{ secrets.DISCORD_BOT_CLIENT_DIRNAME }}/.config
          echo '${{ secrets.BOT_CONFIG }}' > ${{ secrets.DISCORD_BOT_CLIENT_DIRNAME }}/.config/bot_config.toml
          chmod 755 discord_bot_client homeserver_receive_process valheim-connection-check
          zip romira-s_service_manage_bot_release discord_bot_client homeserver_receive_process valheim-connection-check
          mv discord_bot_client ${{ secrets.DISCORD_BOT_CLIENT_DIRNAME }}
      - uses: burnett01/rsync-deployments@5.1
        name: deploy discord bot
        with:
          switches: -avzr --delete
          path: ${{ secrets.DISCORD_BOT_CLIENT_DIRNAME }}
          remote_path: ${{ secrets.BOT_SERVER_PATH }}
          remote_host: ${{ secrets.BOT_SERVER_HOST }}
          remote_port: ${{ secrets.BOT_SERVER_PORT }}
          remote_user: ${{ secrets.BOT_SERVER_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Restart Bot
        uses: fifsky/ssh-action@v0.0.6
        with:
          host: ${{ secrets.BOT_SERVER_HOST }}
          port: ${{ secrets.BOT_SERVER_PORT }}
          user: ${{ secrets.BOT_SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: sudo systemctl restart ${{ secrets.BOT_SERVER_SERVICE_NAME }}
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./romira-s_service_manage_bot_release.zip
          asset_name: romira-s_service_manage_bot_release.zip
          asset_content_type: application/zip
